env:
  global:
    - secure: hO3muck3cWHMhL7hS6OYeYEGL56qE9p8YSHJgKLYF4o+QN7O8imKWlKMTrBe/pKEHVylO3n8bnsDw2+pGVK6FkDvsdiJAPhq5Cx1Hd9R4SjvkKC2Sn9ypT/3CM1wPi6DcawVTuAFleNlc5NujI/ToXonXWQ0D4nimNAdCKntdgMbFs1YbQxVADnW7pbii1wusgtiT6xWyWJwcqTXwW5XJofig7cKHO2fYpi/0nWkug+BGhfeOJ6/fC6GbBJ/7azfGB9Nc+hRNhCbMtHJGbTkuupSVtpxk7TuEwnVDYosWQAjJxaWYSM1eJmvysgC+tvMQgw8haGpgY9xni+nu3HrozEgYYnwnh5+N4TZdn4AczrVEs1n2Y82cQp/++OS4X08+B/HWCN5WDzXRx+HOskAyvE1wA9P/payXZeUfRBqs0Z+mBcRcPxPxM7tIUT2lTBbeTjrzb/Qz4t3Iy3WTGG1T84K5YtOLstTGKBpu5LxW++f2rEGbQA7N3v1l0PiT5ZWgqkB4NgoE7wLxXVRqIV+kjSX/C7Gi1dC5EnCU1XCqA9T3USRuB/SGJxhDuw/Gmde1n/Y7SaQnCwgrMPj7LMIF49qYPIf7r6Zb+FVb+pkSbf7LiKNr3DABuDDInBn8UcoXlRMBbxTtvSKLxXds7TN3qFilNj4yizrOGWGdcCFwRU=
language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
branches:
  only:
    - master
install:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh | bash
  - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/libsodium-1.0.3/lib && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/libsodium-1.0.3/lib
script:
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/deploy_gh-pages.sh | bash
